# Assignment 04 - Pandas

## Company Data Analysis

In this assignment, you will work with the `company_data.csv` dataset to practice various Pandas operations including data loading, cleaning, filtering, and analysis.

**Instructions:** Complete each task by writing your code in the empty cells provided below each question.

In [67]:
%pip install pandas

import pandas as pd

Requirement already satisfied: pandas in /Users/macbook/Developer/AI/machine_learning/env/lib/python3.14/site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in /Users/macbook/Developer/AI/machine_learning/env/lib/python3.14/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/macbook/Developer/AI/machine_learning/env/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/macbook/Developer/AI/machine_learning/env/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

## Task 1: Data Loading & Inspection

Load the `company_data.csv` file into a Pandas DataFrame.

**Requirements:**
- Print the first 10 rows of the dataset
- Use a Pandas method to show the data types of each column
- Check for missing values in each column

In [68]:
df = pd.read_csv(r"./company_data.csv")

In [69]:
print("First 10 rows:")
df.head(10)

First 10 rows:

,Employee_ID,Employee_Name,Department,Salary,Years_Experience,Evaluation_Score,Bonus
0,101,John Doe,IT,85000.0,5,88,5000.0
1,102,Jane Smith,HR,60000.0,3,72,3000.0
2,103,Ali Mansour,Sales,NaN,12,95,7000.0
3,104,Sara Lee,IT,95000.0,1,45,NaN
4,105,Ben Clark,Finance,70000.0,8,60,4000.0
5,106,Eva Green,Sales,55000.0,4,82,2000.0
6,107,Mona Ray,HR,NaN,2,55,NaN
7,108,Leo King,IT,105000.0,10,91,8000.0
8,109,Tom Cook,Finance,72000.0,6,78,4500.0
9,110,Anna Bell,IT,88000.0,9,40,2500.0

In [70]:
print("Data types of each column:")
df.dtypes

Data types of each column:

Employee_ID           int64
Employee_Name           str
Department              str
Salary              float64
Years_Experience      int64
Evaluation_Score      int64
Bonus               float64
dtype: object

In [71]:
print("Missing values per column:")
# df.info() # salary & bonus 17 records
df.isnull().sum()

Missing values per column:

Employee_ID         0
Employee_Name       0
Department          0
Salary              2
Years_Experience    0
Evaluation_Score    0
Bonus               2
dtype: int64

## Task 2: Handling Missing Values

The dataset contains missing values in the `Salary` and `Bonus` columns.

**Requirements:**
- Fill the missing `Salary` values with the median salary of the entire company
- Fill the missing `Bonus` values with 0

In [72]:
salary_median = df['Salary'].median()

df['Salary'] = df['Salary'].fillna(salary_median)
df['Bonus'] = df['Bonus'].fillna(0)

df

,Employee_ID,Employee_Name,Department,Salary,Years_Experience,Evaluation_Score,Bonus
0,101,John Doe,IT,85000.0,5,88,5000.0
1,102,Jane Smith,HR,60000.0,3,72,3000.0
2,103,Ali Mansour,Sales,73500.0,12,95,7000.0
3,104,Sara Lee,IT,95000.0,1,45,0.0
4,105,Ben Clark,Finance,70000.0,8,60,4000.0
5,106,Eva Green,Sales,55000.0,4,82,2000.0
6,107,Mona Ray,HR,73500.0,2,55,0.0
7,108,Leo King,IT,105000.0,10,91,8000.0
8,109,Tom Cook,Finance,72000.0,6,78,4500.0
9,110,Anna Bell,IT,88000.0,9,40,2500.0
10,111,Ryan Gos,Sales,58000.0,2,65,1500.0
11,112,Emma Stone,HR,62000.0,5,89,3500.0
12,113,Will Smith,IT,92000.0,11,77,6000.0
13,114,Kate Wins,Sales,54000.0,1,30,1000.0
14,115,Jack Spar,Finance,75000.0,7,85,5000.0
15,116,Bruce Wayne,IT,110000.0,15,98,9000.0
16,117,Clark Kent,HR,63000.0,4,70,3200.0
17,118,Diana Prince,Sales,59000.0,3,66,2100.0
18,119,Barry Allen,IT,98000.0,9,81,6500.0
19,120,Hal Jordan,Finance,77000.0,6,74,4800.0

## Task 3: Data Cleaning

The `Employee_Name` column is in the format "FirstName LastName".

**Requirements:**
- Split this column into two new columns: `First_Name` and `Last_Name`
- Delete the original `Employee_Name` column

In [73]:
df[['First_Name', 'Last_Name']] = df['Employee_Name'].str.split(' ', n=1, expand=True)

df.drop(columns=['Employee_Name'], inplace=True)

df.head()

,Employee_ID,Department,Salary,Years_Experience,Evaluation_Score,Bonus,First_Name,Last_Name
0,101,IT,85000.0,5,88,5000.0,John,Doe
1,102,HR,60000.0,3,72,3000.0,Jane,Smith
2,103,Sales,73500.0,12,95,7000.0,Ali,Mansour
3,104,IT,95000.0,1,45,0.0,Sara,Lee
4,105,Finance,70000.0,8,60,4000.0,Ben,Clark

## Task 4: Filtering

Create a new DataFrame called `Senior_IT`.

**Requirements:**
- The DataFrame should contain only employees from the 'IT' department
- These employees must have more than 8 years of experience

In [74]:
Senior_IT = df[(df['Department'] == 'IT') & (df['Years_Experience'] > 8)].reset_index(drop=True)

Senior_IT

,Employee_ID,Department,Salary,Years_Experience,Evaluation_Score,Bonus,First_Name,Last_Name
0,108,IT,105000.0,10,91,8000.0,Leo,King
1,110,IT,88000.0,9,40,2500.0,Anna,Bell
2,113,IT,92000.0,11,77,6000.0,Will,Smith
3,116,IT,110000.0,15,98,9000.0,Bruce,Wayne
4,119,IT,98000.0,9,81,6500.0,Barry,Allen

## Task 5: Performance Mapping

Create a new column called `Performance_Level` based on the `Evaluation_Score` (1-100).

**Requirements:**
- Score > 80: "High"
- Score 50-80: "Medium"
- Score < 50: "Low"

In [75]:
df['Performance_Level'] = df['Evaluation_Score'].apply(lambda x: 'High' if x > 80 else ('Medium' if x >= 50 else 'Low'))
df

,Employee_ID,Department,Salary,Years_Experience,Evaluation_Score,Bonus,First_Name,Last_Name,Performance_Level
0,101,IT,85000.0,5,88,5000.0,John,Doe,High
1,102,HR,60000.0,3,72,3000.0,Jane,Smith,Medium
2,103,Sales,73500.0,12,95,7000.0,Ali,Mansour,High
3,104,IT,95000.0,1,45,0.0,Sara,Lee,Low
4,105,Finance,70000.0,8,60,4000.0,Ben,Clark,Medium
5,106,Sales,55000.0,4,82,2000.0,Eva,Green,High
6,107,HR,73500.0,2,55,0.0,Mona,Ray,Medium
7,108,IT,105000.0,10,91,8000.0,Leo,King,High
8,109,Finance,72000.0,6,78,4500.0,Tom,Cook,Medium
9,110,IT,88000.0,9,40,2500.0,Anna,Bell,Low
10,111,Sales,58000.0,2,65,1500.0,Ryan,Gos,Medium
11,112,HR,62000.0,5,89,3500.0,Emma,Stone,High
12,113,IT,92000.0,11,77,6000.0,Will,Smith,Medium
13,114,Sales,54000.0,1,30,1000.0,Kate,Wins,Low
14,115,Finance,75000.0,7,85,5000.0,Jack,Spar,High
15,116,IT,110000.0,15,98,9000.0,Bruce,Wayne,High
16,117,HR,63000.0,4,70,3200.0,Clark,Kent,Medium
17,118,Sales,59000.0,3,66,2100.0,Diana,Prince,Medium
18,119,IT,98000.0,9,81,6500.0,Barry,Allen,High
19,120,Finance,77000.0,6,74,4800.0,Hal,Jordan,Medium

## Task 6: Department Statistics

Calculate statistics for each Department.

**Requirements:**
- Calculate the total salary expense for each department
- Calculate the average evaluation score for each department

In [76]:
total_salary = df.groupby('Department')['Salary'].sum()
print("Total salary expense for each department:")
print(total_salary)

avg_score = df.groupby('Department')['Evaluation_Score'].mean()
print("\nAverage evaluation score for each department:")
print(avg_score)

Total salary expense for each department:
Department
Finance    294000.0
HR         258500.0
IT         673000.0
Sales      299500.0
Name: Salary, dtype: float64

Average evaluation score for each department:
Department
Finance    74.250000
HR         71.500000
IT         74.285714
Sales      67.600000
Name: Evaluation_Score, dtype: float64

## Task 7: Top Earners

Find the top 5 highest-paid employees in the company.

**Requirements:**
- Print only their names and salaries

In [77]:
df.nlargest(n=5, columns=['Salary'])[['First_Name', 'Last_Name', 'Salary']]

   First_Name Last_Name    Salary
15      Bruce     Wayne  110000.0
7         Leo      King  105000.0
18      Barry     Allen   98000.0
3        Sara       Lee   95000.0
12       Will     Smith   92000.0

## Task 8: Salary Update

The company is giving a 10% raise to everyone in the 'Sales' department.

**Requirements:**
- Update the `Salary` column for Sales department employees only
- Apply a 10% increase to their current salary

In [78]:
is_sales_condition = df['Department'] == 'Sales'
df.loc[is_sales_condition, 'Salary'] = df.loc[is_sales_condition, 'Salary'] * 1.10

df

,Employee_ID,Department,Salary,Years_Experience,Evaluation_Score,Bonus,First_Name,Last_Name,Performance_Level
0,101,IT,85000.0,5,88,5000.0,John,Doe,High
1,102,HR,60000.0,3,72,3000.0,Jane,Smith,Medium
2,103,Sales,80850.0,12,95,7000.0,Ali,Mansour,High
3,104,IT,95000.0,1,45,0.0,Sara,Lee,Low
4,105,Finance,70000.0,8,60,4000.0,Ben,Clark,Medium
5,106,Sales,60500.0,4,82,2000.0,Eva,Green,High
6,107,HR,73500.0,2,55,0.0,Mona,Ray,Medium
7,108,IT,105000.0,10,91,8000.0,Leo,King,High
8,109,Finance,72000.0,6,78,4500.0,Tom,Cook,Medium
9,110,IT,88000.0,9,40,2500.0,Anna,Bell,Low
10,111,Sales,63800.0,2,65,1500.0,Ryan,Gos,Medium
11,112,HR,62000.0,5,89,3500.0,Emma,Stone,High
12,113,IT,92000.0,11,77,6000.0,Will,Smith,Medium
13,114,Sales,59400.0,1,30,1000.0,Kate,Wins,Low
14,115,Finance,75000.0,7,85,5000.0,Jack,Spar,High
15,116,IT,110000.0,15,98,9000.0,Bruce,Wayne,High
16,117,HR,63000.0,4,70,3200.0,Clark,Kent,Medium
17,118,Sales,64900.0,3,66,2100.0,Diana,Prince,Medium
18,119,IT,98000.0,9,81,6500.0,Barry,Allen,High
19,120,Finance,77000.0,6,74,4800.0,Hal,Jordan,Medium

## Task 9: Exporting Results

Save the final, cleaned, and updated DataFrame.

**Requirements:**
- Export the DataFrame to a new CSV file
- Name the file `final_employee_report.csv`

In [79]:
df.to_csv(r"./final_employee_report.csv", index=False)